// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID        string  `json:"id"`
	Text      string  `json:"text"`
	CreatedAt string  `json:"createdAt"`
	User      *User   `json:"user"`
	Replies   []*Post `json:"replies"`
	IsReplyOf *Post   `json:"isReplyOf"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Posts []*Post `json:"posts"`
}
